# Generated by Django 4.2.3 on 2023-07-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField()),
                ('std_name', models.CharField(default=False, max_length=250)),
                ('attendance', models.CharField(max_length=250)),
                ('mark', models.CharField(max_length=250)),
            ],
        ),
    ]
