# Generated by Django 4.2.3 on 2023-08-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(default=False, max_length=250)),
                ('attendance', models.CharField(max_length=250)),
            ],
        ),
    ]
