# Generated by Django 4.2.3 on 2023-08-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
