# Generated by Django 4.2.3 on 2023-08-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_attendance_check_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(default=False, max_length=250)),
                ('leave', models.CharField(max_length=250)),
                ('check_attendance', models.BooleanField(default=False)),
            ],
        ),
    ]
